### ISSUE TITLE
Migrate SVG modeline themes to their own package and release

### ISSUE THREAD

**Issue by jasonm23** [ocodo/.emacs.d#3]
- [ ] Use font-awesome or convert specific icons to svg
    - [ ] read-write (pencil)
    - [ ] read-only (ban)
- [ ] Delight, Diminish support - fix minor mode support
- [ ] Major modes as icons... seek community help?
    - [ ] Lisp / Clojure / Elisp / CL / Scheme / Racket etc.
    - [ ] JS
    - [ ] HTML/NXML/XML/SGML
    - [ ] LaTeX, Auctex, Tex
    - [ ] Haskell
    - [ ] Scala
    - [ ] Java
    - [ ] Shell
    - [ ] Markdown
    - [ ] Org
    - [ ] C / C++
    - [ ] Ruby
    - [ ] Python
    - [ ] Perl
    - [ ] CSS / SCSS / LESS / PostCSS
    - ... add more
- [ ] ...

**Comment by dojeda** [comment]
I'll take some time this weekend to understand why the diminish part is not working.

**Comment by jasonm23** [comment]
@dojeda I expect it's because of the way the code gets minor modes.

I has its selected modes and then displays its own abbreviated symbol

This is inherited from Sabof's pack.

I'll rewrite the minor mode management.  

Diminish will hide, delight will shorten.

I will probably do a modeline style/series which has the minor modes listed in a separate row, under the major mode.

**Comment by jasonm23** [comment]
I'll move these topics over to the other repo and close this issue later.

**Comment by dojeda** [comment]
Considering that delight also works with major modes, I'll consider migrating my diminish configuration to delight... I'll keep you up to date

**Comment by jasonm23** [comment]
@dojeda doesn't diminish just hide the minor modes you specify?

**Comment by dojeda** [comment]
The magic behind diminish is still a puzzle to me. This is mostly because my understanding of emacs modes is very limited, but the fact that the diminish docs are interleaved with poems doesn't help.
In any case, with diminish you can hide or re-word:

```
;; hide abbrev-mode
(eval-after-load "abbrev" '(diminish 'abbrev-mode))
;; reword compile-shell-minor-mode
(eval-after-load "compile" '(diminish 'compilation-shell-minor-mode " X"))
```

**Comment by jasonm23** [comment]
Ah, so it does both jobs.  I think perhaps delight also does.

**Comment by dojeda** [comment]
I've fiddled a bit with ocodo-slim-svg-mode-line.el and found a workaround to my problem, without changing my current diminish configuration. 

I finally understood that the mode-line elements are available through the `format-mode-line` function, using different formats. Apparently, there are some useful variables that already provide the usual formats, such as `mode-name` and `mode-line-modes`, among others.

My current workaround is to disable (comment) `smt/minor-mode-indicator-text` and to modify the major-mode widget to include all mode information from `mode-line-modes`:

```
(smt/defwidget major-mode
  :text (lambda (widget)
          ;;(format-mode-line mode-name)) ;; <- this is the original value
          (format-mode-line mode-line-modes)) ;; <- this is the full mode line with diminished or delighted modes
  :on-click (lambda (widget event)
              (message " %s " (format-mode-line mode-line-modes))))
```

The main caveat of this solution is that the click menu does not work. I do not use it, so for the moment I'll leave it as is.

**Comment by jasonm23** [comment]
@dojeda FYI I've released the package via MELPA

the repo is ocodo/ocodo-svg-modelines

**Comment by jasonm23** [comment]
I'll be moving issues over there
